import pandas as pd

IN_PATH = "sample_data/clean_reviews_marine_translated.csv"
OUT_PATH = "sample_data/clean_reviews_marine_translated.csv"  # overwrite in place

df = pd.read_csv(IN_PATH, encoding="utf-8")

manual_translations = {
    6: "- Room: fair.\n- Cleanliness: fair.\n- Comfort: fair.\n- Location: spectacular.\n- Price-quality: expensive.",
    8: "Spectacular location, but lacking maintenance. The towels are more than an ugly color and everything is old.\nAs for the service, the staff couldn't be more serious/unfriendly. Only one waitress smiles at you.\nAs for alcohol, it's forbidden in the restaurant area, and to have a beer you have to go to the resort next door, about 15 minutes away.\nWhat it does have is a spectacular beach, and as soon as you enter you find impressive marine diversity.",
    36: "The hotel is very well located on one of the best beaches. However, for what you pay it's very expensive — they give you torn, worn-out towels, room cleaning is basically nonexistent, they just sweep a little and that's it. Above all, if you go, don't look in the corners of the rooms. It's disgusting.",
    57: 'The location is spectacular, but it\'s the only redeeming thing. The state of the resort and the level of maintenance are simply unacceptable. This is, by far, the worst place I\'ve ever stayed, and I\'ve traveled quite a bit.\n\nTo start, cleaning is completely nonexistent. During the entire stay (six days), they only changed the towels and put out water bottles. They never cleaned the room or the bathroom, nor changed the sheets. One day they forgot to restock the toilet paper (I had to go ask for it at reception); another day, they forgot to empty the trash bin; and on a third day, they simply didn\'t come to "clean" the room at all — we had to complain about that too.\n\nThe facilities are very run-down. The furniture is old, worn, and dirty, the windows are covered in grime, the shower urgently needs renovating, and several things in the room don\'t work properly. On top of that, it lacks the most basic amenities: there\'s no closet or drawers to store clothes. We also found two cockroaches in the bathroom. For this to happen at a place charging these prices is simply unacceptable.\n\nAs for the restaurant food, it\'s expensive and very low quality. Breakfast, besides being scarce, offers minimal variety, and all the food is left uncovered, in a place where flies and mosquitoes roam freely.\n\nIt\'s a shame that a place with such a privileged location is so poorly managed. I had no choice but to book here because, due to circumstances, I looked at accommodations late and this was the only room left. That\'s why I strongly recommend that anyone planning to spend a few days in Perhentian book well in advance, so the same thing doesn\'t happen to you as happened to us. It would be a shame for what could be an unforgettable experience on paradise beaches to become unforgettable for very different reasons.',
    60: "Very good place, very comfortable rooms, right on the beach with all amenities, good restaurant, excellent breakfast.",
    65: "Rooms are a bit small/basic. Insects sneak in at night through the shower drain. Better not to turn on the light at night in the room.",
    77: "Heavenly / Paradise-like",
    90: "Super resort",
    95: 'Please read carefully before coming:\nThis hotel has terrible value for money. The rooms are old, dirty, and poorly maintained.\nThey aren\'t sealed properly, so all kinds of insects and reptiles can get in.\nThis morning we woke up to a swarm of flying termites — there were at least 100 in the room. And that\'s with the doors always kept closed; we never even opened the balcony door once. We even put towels down to try to keep insects out.\nThere\'s no daily room cleaning — I think they just sweep a little near the entrance and give you "clean" towels.\nThere are no food options, not one, believe me, at least not if you don\'t want to get food poisoning. You can basically only survive on ice cream and Pringles, which is what the shop sells.\nBreakfast isn\'t just bad, it\'s disturbing to look at. Nauseating. Full of flies and insects. They don\'t clean the tables between customers — total chaos.\nThe staff don\'t seem happy; they seem bothered whenever you ask them for anything... I don\'t blame them — they\'re working somewhere that surely gets a lot of complaints, and there\'s nothing they can do about it.\n\nIn summary, reconsider coming to this place. Maybe if they changed the name to "Nature Hotel Perhentian" it would be more fitting, because there\'s nothing "Resort" about it.',
    123: "Best room at island",
    134: "Good experience, resort with a private beach and lots of amenities. There are also lots of animals around the property (langur monkeys, monitor lizards, and colugos). The only things that could be improved are the restaurant food and some run-down facilities, like the tennis and badminton courts.",
    139: "I had already read that on the Perhentian Islands most hotels weren't worth what you paid, but I didn't expect this.\nThis hotel, although located on one of the best beaches on Pulau Besar, is old and poorly maintained. It's better to stay at another hotel and just visit this beach for the day.\nThe reason I chose it was because I'd read comments saying the snorkeling at this beach was fantastic. And it's true you can see turtles, but that's about it.\nThe rooms need renovating: the air conditioning smelled really bad, and even though they cleaned the filters, it kept smelling the same. At night it would bring in the smell of the drain outside, and since it was so hot, it was impossible to turn it off.\n- the wooden furniture is scratched and old.\n- and the worst part was the toilet paper dispenser in the bathroom — it was dirty and rusted. You could tell it hadn't been wiped down in years. Disgusting.\nAs for the food:\n- the breakfast buffet was fine\n- for dinner the options are bad, bland, and full of grease. It's much better to go eat at The Barat, which is a 10-minute walk away.\nIn summary, I don't recommend it at all, I wouldn't go back.",
    140: "For me, this is the best hotel in Perhentian. For its location, the beach, and the surroundings.\n\nThe rooms and food aren't the best, but the staff are helpful and carry your bags from the jetty to your room.\n\nI do NOT recommend the bungalows — we switched the next day, there's nothing there and they're extremely uncomfortable.\n\nNotes:\n- there's only wifi in the hall",
    145: "Choosing Taaras Beach for our honeymoon was the best decision we could have made. Our arrival was a bit complicated due to rough waves, but Mrs. Cara treated us wonderfully from start to finish. All the staff are amazing, and we want to give special thanks to Jodi, Jonathan, Hanafi, Izhak, and Roffi for their exceptional kindness and care. To top it off, we were surprised to see sea turtles right on the hotel's beach! We're delighted with our experience and really hope to come back.",
    167: "A paradise....",
    184: "Magical Taaras!",
    233: "We stayed two nights at the Resort, and honestly it's highly recommendable — the location is beautiful, we stayed in one of the suites practically facing the sea. I'd like to highlight the staff service, everyone was super attentive and super kind. We had a very good experience here and fully recommend it.",
    252: "The Falkland Islands are Argentina 🇦🇷",
    253: "very good",
    354: "How can I contact you to make a reservation at your resort?",
    377: "A unique experience. Fantastic. Among giant turtles and exotic fish. Highly recommend 💯. Very friendly staff and good food.",
    410: "We've been here 5 days and loved it. Very pleasant and peaceful stay. The hotel offers a wide variety of activities, from diving to jungle excursions with a very professional guide who's an expert on snakes. Nadia and Alia were very welcoming and kind to us. Thank you so much for your service and help! We'll be back!",
    445: "Perfect! Spacious rooms with an incredible view. The highlight of the 3 nights we spent there: the giant turtles!!!!! Absolutely fantastic, along with the variety of tropical fish. For diving, the experience with Wendy was excellent! We recommend it!\nThe meals were good and the staff were top-notch!\nThank you",
    449: "I came from the other side of the island, via jungle trekking. I ran into some guests who were staying there and they invited me to join them at the restaurant.\nThe security guard wouldn't let me in, even though I was with guests staying there and told him I was coming to eat at the restaurant.",
    499: "We had a fantastic few days of diving with a great team; the boats are in good condition and the guides are excellent. I'm not giving 5 stars because at mealtimes the place fills up with Asian guests who clear out everything very early, and a lot of things don't get restocked afterward, especially the more special fruit. We enjoyed everything except mealtimes. If you do a night dive, you need to let them know in advance, because you'll end up with no dinner at all even if you arrive before closing time. Breakfast is also pretty weak — no yogurt, for example, the bread is terrible, and the only cheese they offer is poor quality.",
    550: "You're in the middle of nowhere. It's a unique experience. The giant turtles at night are beautiful. 💯 Recommended",
    580: "Amazing service",
    612: "Good.",
    693: "Awesome",
    707: "Best for snorkeling 🤿!",
    770: "Great view",
    793: "Very nice experience",
    829: "An experience worth trying. Only recommendable if you like Asian food (there isn't much else to choose from) and if you're doing the diving package (for snorkeling there's not much to do, and there aren't many other activities at the resort).\n\nCut off from the world, perfect for disconnecting.\nThe service is excellent and friendly.",
    901: "Undeniable quality on a dream beach..",
    904: "Good",
    912: "Very smelly n dirty",
    938: "The resort is decent but a bit crowded for my taste. Personally, I felt a little trapped, since you're in the middle of the sea... in the middle of nowhere. So really all you can do is sign up for diving, with or without tanks.\nIt's also not really set up for swimming in the sea and relaxing. If you swim, there's nowhere to sunbathe afterward — sun loungers are only in the rooms.\nThey also offer trips to a small nearby island called Mabul, a 10-minute boat ride from the resort. Not much to it... a small village without much appeal, and you can see it all in 15 minutes.\nThe turquoise water and the brightly colored fish and marine life mean I can only recommend this resort to die-hard diving enthusiasts, since that's really the only thing there is to do.",
    993: "The rooms are very dirty! The bathroom gives off a nauseating smell! Cobwebs pretty much everywhere... the snorkeling club is terribllllle! The restaurant is a real disaster! The only positive point is the location — otherwise there are hotels right nearby that are much better...",
    996: "The best thing about the hotel is its location, on the best beach of all the islands, with incredible views. Crystal-clear water, a meeting point for turtles, small sharks, and manta rays, plus abundant marine life and an impressive variety of fish, all right in front of the room. On the downside, the hotel is quite old and needs renovating and a good facelift. Another downside is the restaurant, possibly the worst quality of all the hotels on the island. Overall I recommend it mainly because it's on the best beach in all of the Perhentians.",
    997: "The hotel is fine, unpretentious — spacious, clean rooms with a very pleasant porch to sit and read or have a drink.\nThe bathroom is very small but clean.\nBreakfast is decent, but the restaurant for lunch and dinner is terrible — bad, expensive fast food.\nWithout a doubt, the hotel's strong point is its location, on Turtle Beach, which is the best of all the Perhentians. For that reason alone I'd definitely recommend it, because in the end there aren't that many hotel options and this one meets the minimum requirements while being on the best beach.\nI'd recommend going to eat at Coral View next door.",
    1001: "so rude with customers",
    1034: 'The location and the beach in front of the hotel are, without a doubt, THE BEST ON THE ISLAND — that\'s the positive part. The negatives:\n\n1- The hotel restaurant needs a lot of improvement. Prices are a bit higher than in other areas, which would be fine if the food were good, but it isn\'t (except for a few specific dishes). You can tell no one\'s really keeping an eye on things, no manager supervising. Breakfast is basic but fine.\n\n2- The rooms are THE WORST PART — maintenance is basically NONEXISTENT. Walls, closets, floors — everything is worn out and old. If that were all, the rating would be higher, but no — CLEANLINESS NEEDS TO BE IMPLEMENTED. There are no mosquito nets on the beds; last night we had to kill, without exaggeration, 15 tiny insects I couldn\'t identify, they looked like mini-mosquitoes. Given that we always kept everything closed and shut the door right away, I understand you\'re in the jungle and there will be bugs, but not in that quantity — they need to put measures in place so this doesn\'t happen. We paid €113 per night (for a standard room, not near the sea), not €30. And what really left us speechless was finding a large amount of some kind of sandy grit under the bed — after looking into it a bit, it seems to be termite droppings, I\'m NOT SURE, but it definitely wasn\'t sand. In conclusion, you don\'t sleep comfortably.\n\n3- The service: it\'s true we met some pleasant people, but there were others who weren\'t particularly friendly.\n\nI don\'t know if this is an isolated situation or not, since we haven\'t stayed at other hotels on this island — I don\'t know how common it is, but we stayed at Ombak Resort (on Kecil) and it was much better, both the restaurant, the rooms, and the service.',
    1035: 'The beach is paradise, but the resort is hell.\n\nDirty rooms, no real cleaning (they only change towels, they don\'t even restock toilet paper or water), old facilities full of dampness. The restaurant is chaotic: no one serves you, the food is terrible and expensive, and they don\'t serve alcohol (which isn\'t mentioned anywhere). The dive center wasn\'t even able to offer a private instructor.\n\nWe ended up salvaging our vacation at the neighboring resort, The Barat, where they treated us well and I was able to dive with an excellent private instructor.\n\nConclusion: this hotel survives purely on its location. The beach is unique, but the "resort" is in a state of neglect and ruins the experience.',
    1047: 'They call themselves a resort hotel, but all they really are is a handful of old rooms facing a turquoise beach, with absolutely deplorable service. This place was the biggest disappointment of my trip.||The Illusion of the Paradise Beach||||At first glance, the beach may seem like paradise, but the reality is different. Despite having turquoise water, the marine environment is a complete disappointment. There\'s no living coral reef; it\'s all dead coral sand with barely any fish in sight. If you\'re looking to snorkel or dive, you have to swim to an extreme depth to, with luck, find a turtle.||||Rooms and Maintenance: Old and Dirty||The rooms are old and in a state of total neglect, and nothing justifies the price. Cleaning is nonexistent: staff didn\'t restock the toilet paper and the room conditions were unacceptable. In the bathroom we found mold in the grout and faucets covered in limescale, plus damp stains on the ceiling. Outside, the scene was bleak, with piles of trash and debris scattered around the property.||||Services: Nonexistent and Disappointing||Service, in general, is dreadful. Reception staff are unfriendly and don\'t provide information. But the most serious issue was the dive center, which was one of the main reasons for our visit. We went to ask about booking a private day and two dives, and we were simply told it wasn\'t possible, which ruined the experience.||||The Food: A Real Scam||The restaurant deserves its own chapter. The breakfast buffet is poor and limited, and the food is so bad we had to go eat at nearby restaurants instead. The prices are outrageous for the extremely low quality on offer. Also, future guests should know the hotel doesn\'t serve alcoholic drinks.||Conclusion||||Don\'t be fooled by the word "resort". This place lacks everything it promises: no cleanliness, no good service, no good food, no living reef. If you value a quality experience, I strongly recommend you look for another hotel.',
    1051: "We stayed in one of the beachfront rooms. The view is stunning, the water is crystal clear, and you can hear the waves from the bed. However, the interior leaves a lot to be desired. The sheets had stains, the furniture is very outdated, and insects come out of the bathroom every time you use the toilet or shower. It gives a very old and dirty impression. The restaurant staff aren't the friendliest, but the food is edible. The tablecloths might not have been washed in years...",
    1078: "Very well-located hotel, with an excellent paradise-like beach. Shame about the boats constantly coming and going... restaurant with a decent buffet and menu. The room... we got the \"Deluxe Heaven\"... it's a piece of s***... horrible... really gives you the creeps... lucky the location is spot-on.",
    1116: "This hotel must have been great at some point, but now it's outdated and completely neglected. The buffet is pitiful — ants running all over the food. The rooms are fine, but we found salamanders inside the cabin, and on the second night we suffered a bedbug attack. It's very expensive for what it is. They take advantage of being the only option — take it or leave it.\nSuch a shame, because the location is ideal and guests could leave very happy.",
    1140: "Great for snorkeling here",
    1160: "Very good",
    1188: "Sooo fun for family time",
}

applied, missing = 0, []
for idx, translation in manual_translations.items():
    if idx in df.index:
        df.at[idx, "text"] = translation
        df.at[idx, "translation_status"] = "translated_manual"
        applied += 1
    else:
        missing.append(idx)

df.to_csv(OUT_PATH, index=False, encoding="utf-8")

print(f"Applied {applied} manual translations.")
if missing:
    print(f"WARNING: these row_index values were not found in the dataframe: {missing}")
print("\nStatus breakdown:")
print(df["translation_status"].value_counts())